//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetfairNG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetfairNG.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Abbreviation
        ///Aintree,Aint
        ///Ascot,Ascot
        ///Ayr,Ayr
        ///Ballinrobe,Ballin
        ///Bangor,Bang
        ///Bath,Bath
        ///Bellewstown,Belle
        ///Beverley,Bev
        ///Brighton,Brig
        ///Carlisle,Carl
        ///Cartmel,Cart
        ///Catterick,Catt
        ///Cheltenham,Chelt
        ///Chepstow,Chep
        ///Chester,Chest
        ///Clonmel,Clon
        ///Cork,Cork
        ///Doncaster,Donc
        ///Down Royal ,DownR
        ///Downpatrick,DownP
        ///Dundalk,Dund
        ///Epsom,Epsm
        ///Exeter,Extr
        ///Fairyhouse,Fairy
        ///Fakenham,Fake
        ///Folkstone,Folk
        ///Fontwell,Font
        ///Galway,Gal
        ///Goodwood,Good
        ///Gowran Park,GowP
        ///Hamilton,Ham
        ///Haydock,Hayd
        ///Hereford,Here
        ///Hex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RaceCourseAbbreviation {
            get {
                return ResourceManager.GetString("RaceCourseAbbreviation", resourceCulture);
            }
        }
    }
}
