//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetfairNG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetfairNG.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,eventType_id,eventType_Name
        ///1,27454571,Esports
        ///2,7,Horse Racing
        ///3,3503,Darts
        ///4,1,Soccer
        ///5,7524,Ice Hockey
        ///6,2378961,Politics
        ///7,10,Special Bets
        ///8,5,Rugby Union
        ///9,7511,Baseball
        ///10,6423,American Football
        ///11,7522,Basketball
        ///12,61420,Australian Rules
        ///13,2,Tennis
        ///14,998917,Volleyball
        ///15,3,Golf
        ///16,4,Cricket
        ///17,11,Cycling
        ///18,6,Boxing
        ///19,1477,Rugby League
        ///20,8,Motor Sport
        ///21,2152880,Gaelic Games
        ///22,6422,Snooker
        ///23,4339,Greyhound Racing
        ///24,28361978,Lottery Specials
        ///25,3988,Athletics
        ///26,26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventTypes {
            get {
                return ResourceManager.GetString("EventTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Abbreviation
        ///Aintree,Aint
        ///Ascot,Ascot
        ///Ayr,Ayr
        ///Ballinrobe,Ballin
        ///Bangor,Bang
        ///Bath,Bath
        ///Bellewstown,Belle
        ///Beverley,Bev
        ///Brighton,Brig
        ///Carlisle,Carl
        ///Cartmel,Cart
        ///Catterick,Catt
        ///Cheltenham,Chelt
        ///Chepstow,Chep
        ///Chester,Chest
        ///Clonmel,Clon
        ///Cork,Cork
        ///Doncaster,Donc
        ///Down Royal ,DownR
        ///Downpatrick,DownP
        ///Dundalk,Dund
        ///Epsom,Epsm
        ///Exeter,Extr
        ///Fairyhouse,Fairy
        ///Fakenham,Fake
        ///Folkstone,Folk
        ///Fontwell,Font
        ///Galway,Gal
        ///Goodwood,Good
        ///Gowran Park,GowP
        ///Hamilton,Ham
        ///Haydock,Hayd
        ///Hereford,Here
        ///Hex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RaceCourseAbbreviation {
            get {
                return ResourceManager.GetString("RaceCourseAbbreviation", resourceCulture);
            }
        }
    }
}
